- name: Playbook
  hosts: VM
  become: yes
  tasks:
    - name: enable and start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
    - name: permit traffic on 8080/tcp
      ansible.posix.firewalld:
        port: 8080
        permanent: yes
        state: enabled
        immediate: yes
    - name: Copy file
      ansible.builtin.copy:
        src: hostfile.log
        dest: /home/jenkins
